# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-07 18:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_name', models.CharField(max_length=200)),
                ('case_function', models.CharField(choices=[('noun', 'Noun'), ('verb', 'Verb'), ('adj', 'Adjective'), ('adv', 'Adverb')], default='noun', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Definition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('definition_text', models.TextField()),
                ('definition_example', models.TextField()),
                ('definition_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='definition', to='lexicon.Case')),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='case_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case', to='lexicon.Entry'),
        ),
    ]
