# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-07 21:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lexicon', '0006_auto_20160107_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='case_example',
        ),
    ]
